version: "3.6"
services:
  mygoservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-monitoring/latest
    ports:
    - 8000:8000
  prometheus:
    image: prom/prometheus
    configs:
    - source: prometheus-conf
      target: /etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
configs:
  prometheus-conf:
    file: ./prometheus/prometheus.yml
